# Generated by Django 5.0 on 2024-01-16 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phnumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('foodId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemStatus',
            fields=[
                ('statusId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status_name', models.CharField(max_length=255)),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.customer')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rname', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.branch')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.restaurant'),
        ),
    ]
