# Generated by Django 5.0 on 2024-01-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kitchen_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
